### ISSUE TITLE
Updating .txt files

### ISSUE THREAD

**Issue by daisukedd** [floh22/LeagueBroadcastConnect#1]
The generated files are not being updated in real time and only the red team is showing

**Comment by shinilee** [comment]
me too
![image](https://user-images.githubusercontent.com/82671596/125341729-f643da80-e321-11eb-840e-569e6405df1c.png)
mine only generated blue but and not updated

**Comment by floh22** [comment]
Fixed in [v1.0.103](https://github.com/floh22/LeagueBroadcastConnect/releases/tag/v1.0.103)
